export const ASSURES_STRUCTURE = {
  list: {
    title: 'Assurés',
    create: 'Nouvel assuré',
    search: 'Rechercher un assuré',
    searchHint: 'Nom, société, email, téléphone ou ville',
    columns: { name: 'Assuré', type: 'Type', email: 'Email', phone: 'Téléphone', city: 'Ville' },
    empty: "Aucun assuré pour le moment. Créez le premier pour démarrer un dossier.",
    noResult: 'Aucun assuré ne correspond à votre recherche.',
    loading: 'Chargement des assurés…',
    pageSize: 'Assurés par page',
  },
  types: [
    { value: 'particulier', label: 'Particulier' },
    { value: 'pro', label: 'Professionnel' },
  ],
  typeLabels: { particulier: 'Particulier', pro: 'Professionnel' },
  civilites: [
    { value: '', label: '—' },
    { value: 'M.', label: 'M.' },
    { value: 'Mme', label: 'Mme' },
  ],
  form: {
    createTitle: 'Nouvel assuré',
    identity: 'Identité',
    contact: 'Coordonnées',
    address: 'Adresse',
    type: "Type d'assuré",
    civilite: 'Civilité',
    firstName: 'Prénom',
    lastName: 'Nom',
    companyName: 'Raison sociale',
    siret: 'SIRET',
    birthDate: 'Date de naissance',
    email: 'Email',
    phone: 'Téléphone',
    street: 'Adresse',
    postalCode: 'Code postal',
    city: 'Ville',
    errors: {
      required: 'Ce champ est obligatoire',
      email: "L'email n'est pas valide",
      phone: 'Numéro de téléphone français attendu (ex. 06 12 34 56 78)',
      siret: 'Le SIRET comporte 14 chiffres',
      birthDate: "La date de naissance n'est pas valide",
      postalCode: 'Le code postal comporte 5 chiffres',
    },
    create: "Créer l'assuré",
    createAnyway: 'Créer quand même',
    save: 'Enregistrer',
    saveAnyway: 'Enregistrer quand même',
    cancel: 'Annuler',
  },
  duplicate: {
    title: 'Cet assuré existe peut-être déjà',
    sameEmail: 'même email',
    sameIdentity: 'même nom et même date de naissance',
    open: 'Ouvrir la fiche',
  },
  detail: {
    back: 'Retour aux assurés',
    notFound: 'Assuré introuvable.',
    infoTitle: 'Informations',
    dossiersTitle: 'Dossiers',
    noDossiers: "Aucun dossier pour cet assuré pour l'instant.",
    columns: { reference: 'Référence', product: 'Produit', status: 'Statut', createdAt: 'Créé le' },
    draftReference: 'Brouillon',
  },
} as const;
