export const DOSSIERS_STRUCTURE = {
  list: {
    title: 'Dossiers',
    create: 'Nouveau dossier',
    mine: 'Mes dossiers',
    filters: { status: 'Statut', product: 'Produit', courtier: 'Courtier', all: 'Tous', allProducts: 'Tous', allCourtiers: 'Tous' },
    reset: 'Réinitialiser les filtres',
    columns: { reference: 'Référence', assure: 'Assuré', product: 'Produit', status: 'Statut', courtier: 'Courtier', createdAt: 'Créé le' },
    empty: 'Aucun dossier pour le moment. Créez le premier pour démarrer une tarification.',
    noResult: 'Aucun dossier ne correspond à ces filtres.',
    loading: 'Chargement des dossiers…',
    resume: 'Reprendre',
    pageSize: 'Dossiers par page',
  },
  stepper: {
    steps: ['Assuré', 'Produit', 'Questionnaire', 'Récapitulatif'],
  },
  newDossier: {
    title: 'Nouveau dossier',
    assureTitle: "Pour quel assuré ?",
    assureSearch: 'Rechercher un assuré',
    assureHint: 'Nom, société, email ou téléphone',
    noAssure: 'Aucun assuré trouvé.',
    createAssure: 'Créer un nouvel assuré',
    productTitle: 'Quel produit ?',
    noProduct: "Aucun produit n'est disponible. Un administrateur doit publier le catalogue ou activer des produits dans Paramètres.",
    next: 'Continuer',
    back: 'Retour',
    cancel: 'Annuler',
    draftNote: 'Le dossier est enregistré en brouillon dès le passage à l’étape suivante.',
    creating: 'Création du dossier…',
  },
  draft: {
    section: 'Section',
    of: 'sur',
    previous: 'Précédent',
    next: 'Suivant',
    toSummary: 'Récapitulatif',
    summaryTitle: 'Récapitulatif',
    backToQuestionnaire: 'Retour au questionnaire',
    saveAndQuit: 'Enregistrer et quitter',
    validate: 'Marquer le dossier complet',
    complete: 'Toutes les informations obligatoires sont renseignées.',
    missingTitle: 'Informations obligatoires manquantes',
    missingHint: 'Le dossier ne peut pas passer en « complet » tant qu’elles ne sont pas renseignées.',
    goTo: 'Renseigner',
    assure: 'Assuré',
    product: 'Produit',
    saving: 'Enregistrement…',
    saved: 'Brouillon enregistré',
    dirty: 'Modifications non enregistrées',
    error: 'Échec de l’enregistrement',
    notFound: 'Dossier introuvable.',
  },
  detail: {
    back: 'Retour aux dossiers',
    notFound: 'Dossier introuvable.',
    tabs: { infos: 'Infos', history: 'Historique', need: 'Besoin', pricing: 'Tarification', comparison: 'Comparatif', proposal: 'Proposition' },
    assignedTo: 'Courtier en charge',
    resume: 'Reprendre le brouillon',
    save: 'Enregistrer les modifications',
    readonlyNote: 'Ce dossier n’est plus modifiable à ce stade.',
    missingBanner: 'Informations obligatoires manquantes :',
    statusActions: {
      brouillon: 'Repasser en brouillon',
      complet: 'Marquer complet',
      sans_suite: 'Classer sans suite',
    } as Record<string, string>,
    incompleteHint: 'Complétez les champs obligatoires pour passer le dossier en « complet ».',
    confirmSansSuite: 'Classer ce dossier sans suite ? Cette action est définitive.',
  },
  timeline: {
    title: 'Historique',
    empty: 'Aucun événement.',
    created: 'Dossier créé',
    dataUpdated: 'Informations modifiées',
    statusChanged: 'Statut',
    automatic: 'changement automatique (une information obligatoire a été retirée, ou le besoin a été modifié)',
    assigned: 'Assigné à',
    needUpdated: 'Besoin modifié',
    note: 'Note',
    pricingRequested: 'Tarification demandée',
    pricingRetried: 'Tarification relancée',
    pricingCompleted: 'Informations manquantes complétées',
    offerEntered: 'Offre saisie manuellement',
    decisionMade: 'Offre retenue',
    proposalSent: 'Proposition envoyée',
    proposalResent: 'Proposition renvoyée',
    proposalReminder: 'Relance envoyée au courtier',
    outcome: { souscrit: 'Contrat souscrit', refuse: 'Proposition refusée', sans_suite: 'Classé sans suite' } as Record<string, string>,
    unknownMember: 'un membre',
  },
} as const;
