export const SETTINGS_STRUCTURE = {
  title: 'Paramètres du cabinet',
  tabs: { cabinet: 'Cabinet', members: 'Membres', catalog: 'Assureurs et produits', audit: 'Connexions' },

  cabinet: {
    logoTitle: 'Logo',
    logoHint: 'PNG, JPG ou SVG, 2 Mo maximum. Il apparaîtra sur les propositions envoyées aux clients.',
    logoButton: 'Choisir un logo',
    logoTooBig: 'Le logo dépasse 2 Mo.',
    infoTitle: 'Informations',
    name: 'Nom du cabinet',
    nameRequired: 'Le nom est obligatoire',
    orias: 'Numéro ORIAS',
    oriasInvalid: 'Le numéro ORIAS comporte 8 chiffres',
    address: 'Adresse',
    phone: 'Téléphone',
    email: 'Email de contact',
    emailInvalid: "L'email n'est pas valide",
    save: 'Enregistrer',
  },

  members: {
    inviteTitle: 'Inviter un collaborateur',
    seats: 'Utilisateurs',
    limitReached:
      "Votre cabinet a atteint sa limite d'utilisateurs. Désactivez un membre ou annulez une invitation pour libérer une place.",
    cancelInvitation: 'Annuler',
    inviteHint: "Il recevra un email avec un lien pour rejoindre le cabinet (valable 7 jours).",
    email: 'Email',
    emailInvalid: "L'email n'est pas valide",
    role: 'Rôle',
    invite: 'Inviter',
    listTitle: 'Membres',
    columns: { member: 'Membre', role: 'Rôle', device: 'Appareil', status: 'Statut' },
    noDevice: 'Aucun appareil lié',
    deviceSince: 'lié le',
    lastSeen: 'actif le',
    resetDevice: "Réinitialiser l'appareil",
    resetDevices: 'Réinitialiser les appareils',
    devicesPerUser: 'Appareils par utilisateur',
    resetSelfHint: 'Votre appareil ne peut être réinitialisé que par un autre administrateur ou par le support.',
    confirmReset: 'Confirmer',
    cancelReset: 'Annuler',
    resetsThisMonth: "Réinitialisations d'appareil ce mois-ci",
    resetsExhausted: "Quota de réinitialisations atteint pour ce mois : réessayez le mois prochain ou changez d'offre.",
    you: 'vous',
    active: 'Actif',
    disabled: 'Désactivé',
    disable: 'Désactiver',
    enable: 'Réactiver',
    pendingTitle: 'Invitations en attente',
    expiresOn: 'expire le',
  },

  catalog: {
    title: 'Assureurs et produits actifs',
    hint: "Seuls les assureurs et produits cochés sont proposés dans votre cabinet (dossiers, tarification, comparatif).",
    productsTitle: 'Produits',
    insurersTitle: 'Assureurs',
    noProducts: 'Aucun produit au catalogue pour le moment.',
    noInsurers: 'Aucun assureur au catalogue pour le moment.',
    save: 'Enregistrer',
  },

  audit: {
    title: 'Journal des connexions et des appareils',
    hint: 'Les 50 dernières actions : connexions, appareils liés, refus et réinitialisations.',
    empty: 'Aucune activité enregistrée pour le moment.',
    columns: { date: 'Date', member: 'Membre', event: 'Événement' },
    unknownMember: 'Membre supprimé',
    events: {
      connexion: 'Connexion',
      connexion_refusee_appareil: 'Connexion refusée : appareil non autorisé',
      appareil_lie: 'Appareil lié au compte',
      extension_connexion: "Extension Chrome connectée",
      appareil_reinitialise: 'Appareil réinitialisé par un administrateur',
      reinitialisation_refusee_quota: 'Réinitialisation refusée : quota mensuel atteint',
    },
    device: 'Appareil',
  },

  roles: [
    { value: 'courtier', label: 'Courtier' },
    { value: 'admin', label: 'Administrateur' },
  ],
} as const;
