export const PROPOSAL_STRUCTURE = {
  offerTitle: 'Offre retenue',
  noOffer: 'L’offre retenue est introuvable.',
  premiumAnnual: 'Prime annuelle',
  premiumMonthly: 'Prime mensuelle',
  deductibles: 'Franchises',
  generalDeductible: 'Franchise générale',
  guarantees: 'Garanties incluses',
  limit: 'plafond',
  justification: 'Justification',
  sendTitle: 'Envoyer la proposition',
  recipient: 'Email du destinataire',
  recipientHint: 'Par défaut, l’email de l’assuré.',
  message: 'Message personnalisé (facultatif)',
  send: 'Envoyer la proposition',
  resend: 'Renvoyer',
  sent: 'Proposition envoyée',
  sentOn: 'le',
  sentTo: 'à',
  reminders: 'Relance(s) du courtier',
  lastReminder: 'dernière le',
  answerTitle: 'Réponse de l’assuré',
  subscribed: 'Souscrit',
  refused: 'Refusé',
  noFollowUp: 'Sans suite',
  confirmRefused: 'Enregistrer le refus de l’assuré ? Le dossier sera clos.',
  confirmNoFollowUp: 'Classer ce dossier sans suite ? Le dossier sera clos.',
  sentMessage: 'Proposition envoyée.',
  answerSaved: 'Réponse enregistrée.',
  outcome: {
    souscrit: 'Contrat souscrit',
    refuse: 'Proposition refusée par l’assuré',
    sans_suite: 'Dossier classé sans suite',
  } as Record<string, string>,
  contractNumber: 'N° de contrat',
  effectiveDate: 'Date d’effet',
  decidedOn: 'Enregistré le',
  dialog: {
    title: 'Contrat souscrit',
    contractNumber: 'Numéro de contrat',
    effectiveDate: 'Date d’effet (AAAA-MM-JJ)',
    cancel: 'Annuler',
    confirm: 'Enregistrer la souscription',
  },
} as const;
